### ISSUE TITLE
Request to set CsWinRTWindowsMetadata to 10.0.22621.0

### ISSUE THREAD

**Issue by wherewhere** [dongle-the-gadget/CsWinRTProjectionForWindows#2]
Many apis such as `TryCreateBlurredWallpaperBackdropBrush` dosen't included in this project. Set `CsWinRTWindowsMetadata` to `10.0.22621.0` can fix it.
![image](https://user-images.githubusercontent.com/27689196/233994628-11041ce5-ee31-4555-a724-cff7541bfbba.png)

**Comment by dongle-the-gadget** [comment]
Should be fixed with 10.0.22621.756 and 10.0.22000.198
<img width="1128" alt="Screenshot of ILSpy, showing the Windows.UI.Composition.Compositor.TryCreateBlurredWallpaperBackdropBrush method" src="https://user-images.githubusercontent.com/29563098/236213102-ca6c41af-6263-461e-9dea-71236333f9d0.png">
